version: '3.8'
services:
  ohc-rosters-bot:
    image: ohctyler/ohc-rosters-bot:latest
    container_name: ohc-rosters-bot
    restart: always
    env_file: .env
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    volumes:
      - /volume1/docker/ohc-rosters-bot-data:/app/data:rw
    command: ["npm", "start"]
