version: '3.8'
services:
  ohc-rosters-bot:
    image: yourname/ohc-rosters-bot:latest
    # For local dev without pushing, you can build from source:
    # build: .
    container_name: ohc-rosters-bot
    restart: always
    env_file: .env
    volumes:
      - ohc_rosters_data:/app/data
    command: ["npm", "start"]

volumes:
  ohc_rosters_data:
