version: '3.8'
services:
  ohc-rosters-bot:
    image: ohctyler/ohc-rosters-bot:latest
    container_name: ohc-rosters-bot
    restart: always
    env_file: .env
    # Use your host path for the DB and snapshots
    volumes:
      - ./:/app
    command: ["npm", "start"]
