# .github/workflows/dockerhub.yml
name: Build & Push to Docker Hub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}  # allow manual run from Actions tab

env:
  IMAGE_NAME: ohc-rosters-bot
  DOCKERHUB_NAMESPACE: ohctyler  # <- your Docker Hub username (lowercase)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # <- UPPERCASE
          password: ${{ secrets.DOCKERHUB_TOKEN }}     # <- UPPERCASE

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: docker.io/${{ env.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
